parser: babel-eslint

plugins:
  - flowtype
  - import
  - prettier

extends:
  - airbnb-base
  - prettier
  - plugin:prettier/recommended

env:
  node: true
  browser: false

rules:

  prettier/prettier: error

  eqeqeq: [off, smart]
  no-unused-expressions: off
  consistent-return: off
  no-dupe-keys: error
  no-console: off

  import/no-extraneous-dependencies: off
  import/prefer-default-export: off

  flowtype/define-flow-type: error
  flowtype/no-dupe-keys: error
  flowtype/no-flow-fix-me-comments: off
  flowtype/no-mutable-array: error
  flowtype/no-primitive-constructor-types: error
  flowtype/no-types-missing-file-annotation: error
  flowtype/no-unused-expressions: off
  flowtype/no-weak-types: off
  flowtype/require-exact-type: off
  flowtype/require-parameter-type: [off, { excludeParameterMatch: '^_[0-9]*$' }]
  flowtype/require-return-type: off
  flowtype/require-valid-file-annotation: [error, never, { annotationStyle: block }]
  flowtype/require-variable-type: off
  flowtype/sort-keys: off
  flowtype/type-id-match: [error, '^[A-Z][a-z0-9]*']
  flowtype/use-flow-type: error
